### ISSUE TITLE
Registration matching passwords bug

### ISSUE THREAD

**Issue by jeffreyxchan** [ideahacks/ideahacks.la#164]
When you fail to input matching passwords on the registration page, it erases everything. This shouldn't be happening. The most it should do is just remove the passwords from the page. It should not remove everything.

Is either a problem with the jquery that is handling the input clearing, or an issue with the backend sending the wrong status.

**Comment by fkennedy** [comment]
Ideally validation should be done on the frontend (at least for matching passwords)
