### ISSUE TITLE
User update does not check for duplicate emails.

### ISSUE THREAD

**Issue by rzalog** [ideahacks/ideahacks.la#311]
When you POST to update user information, the backend does not check that the user email already exists. This allows you to have two users with the same email in the DB at the same time. The issue is specifically in `ideahacks/routes/dashboard/dashboard.js`, where you can just add a check that the email address is not in the DB before updating the address.

**Comment by jeffreyxchan** [comment]
Good catch! This will hopefully be resolved with #312 .

The solution I chose was to configure the User schema to recognize the email field as unique
```js
email: {type: string, unique: true}
```
and so calling the `save()` function on a different user that has the same email as someone else should cause an error, which is caught by a handler and sent back to the client.

The error message might not be very readable. Currently no tests to test if this will work.

**Comment by jeffreyxchan** [comment]
Confirmed that this works in dev with a beautiful error message, so closing :)

![image](https://user-images.githubusercontent.com/16298586/60157683-361fdf80-97a4-11e9-985c-21ad26883335.png)
