### ISSUE TITLE
Parts creation should be able to read CSV/create parts in bulk

### ISSUE THREAD

**Issue by robertnperalta** [ideahacks/ideahacks.la#460]
There is little reason for parts to be created one-by-one from an admin account. Generally, there is a parts list spreadsheet already, and giving a whole committee (usually Operations) admin access can be iffy, particularly when applications are still under review.

A much more convenient way of creating parts would be to allow users to fill a spreadsheet of a predetermined format with all of the parts information, then export it as CSV and paste/upload to the website. This would also allow checks for consistency between parts (i.e. unique names/barcodes for each part) without interacting with the database.

**Comment by paulzzy** [comment]
Created a Google Sheets just for parts. Maximum fancy. Code at https://github.com/ideahacks/mugs.
